version: '3.1'
services:
  mysql:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=hc_archives_back
      - MYSQL_USER=hc_archives_back
      - MYSQL_PASSWORD=example
      
  hc_archives_back:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    environment:
      - DATABASE_URL=mysql+pymysql://root:example@mysql/hc_archives_back
    ports:
      - "8000:5000"