"""didnt keep track of updates but adding whatever has been changed since

Revision ID: a66d3f51e66e
Revises: 8b8d9cfbe8be
Create Date: 2025-01-14 15:45:37.126383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a66d3f51e66e'
down_revision = '8b8d9cfbe8be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track', schema=None) as batch_op:
        batch_op.add_column(sa.Column('track_number', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track', schema=None) as batch_op:
        batch_op.drop_column('track_number')

    # ### end Alembic commands ###
